//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//
package com.mysampleapp;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;

import com.amazonaws.mobile.AWSMobileClient;
import com.amazonaws.mobilehelper.auth.IdentityManager;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    /** Class name for log messages. */
    private static final String LOG_TAG = MainActivity.class.getSimpleName();


    /** The identity manager used to keep track of the current user account. */
    private IdentityManager identityManager;

    /** Data to be passed between fragments. */
    private Bundle fragmentBundle;


    public void showUserPantry() {

        Intent intent = new Intent(getApplicationContext(), ListDataActivity.class);
        startActivity(intent);
    }

    public void showUserRecipe() {

        Intent intent = new Intent(getApplicationContext(), UserRecipeActivity.class);
        startActivity(intent);
    }



    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Obtain a reference to the mobile client. It is created in the Application class,
        // but in case a custom Application class is not used, we initialize it here if necessary.
        AWSMobileClient.initializeMobileClientIfNecessary(this);

        // Obtain a reference to the mobile client. It is created in the Application class.
        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        // Obtain a reference to the identity manager.
        identityManager = awsMobileClient.getIdentityManager();

        setContentView(R.layout.activity_user_home);

        setTitle("Pantry2Pan");
        Button recipeButton = (Button) findViewById(R.id.recipeButton);
        recipeButton.setOnClickListener(this);

        Button pantryButton = (Button) findViewById(R.id.pantryButton);
        pantryButton.setOnClickListener(this);

    }



    @Override
    public void onClick(final View view) {

        // ... add any other button handling code here ...
        if (view.getId() == R.id.recipeButton) {
            showUserRecipe();
        }
        else if(view.getId()== R.id.pantryButton){
            showUserPantry();
        }
    }

}